title       = "mavencentral"
baseURL     = "https://mavencentral-cli.tamnd.com/"
description = "A command line for Maven Central."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/mavencentral-cli"
